# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : Timothy's Note
tagline             : 'aaaa_tagline'
description         : 'Recording What I Learn And What I Like.'
baseurl             : https://ssj0936.github.io/

author              : Timothy Chung
name                : 'Timothy'
url                 : https://ssj0936.github.io/
facebook_username   : ssj0936
paginate            : 10

# Custom vars
version             : 0.1.0
# twitter_username    : 
github_username     : ssj0936
